import type { GetStaticProps, NextPage } from 'next'
import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { keys } from '../config'

const Home: NextPage = () => {

  const [movies, setMovies] = useState<IMovie[]>([])
 
  useEffect(() => {

    let newMovies: IMovie[] = [];

    fetch(`https://api.themoviedb.org/3/movie/top_rated?api_key=${keys.apiKey}`)
    .then(res => {
      return res.json()
    })
    .then(data => {

      if(data.results && data.results.length > 1){

         newMovies = data.results as IMovie[];

        setMovies([...newMovies])

      }

    })
  
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        {
          
          movies.length > 0 && movies.map((movie, i) => (
            <li key={i}>
              {movie.title}
            </li>
          ))

        }
      </main>

    </div>
  )
}


interface IMovie {
  title: string
}


export default Home
